// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcvyyhv3LBt30E62SBIfO0o0CPxA6KXR4',
    appId: '1:399269825726:web:526f02007b81aab64ea2ef',
    messagingSenderId: '399269825726',
    projectId: 'spotifyproj0707',
    authDomain: 'spotifyproj0707.firebaseapp.com',
    storageBucket: 'spotifyproj0707.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvl4LRktJqWgD4QhZya_JaSNBDNdis8X4',
    appId: '1:399269825726:android:dcc0fb1b4d8a99014ea2ef',
    messagingSenderId: '399269825726',
    projectId: 'spotifyproj0707',
    storageBucket: 'spotifyproj0707.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEueZOc1-rRRXJTYSSrAblXHqxgxD89es',
    appId: '1:399269825726:ios:28deb54aee8170254ea2ef',
    messagingSenderId: '399269825726',
    projectId: 'spotifyproj0707',
    storageBucket: 'spotifyproj0707.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEueZOc1-rRRXJTYSSrAblXHqxgxD89es',
    appId: '1:399269825726:ios:28deb54aee8170254ea2ef',
    messagingSenderId: '399269825726',
    projectId: 'spotifyproj0707',
    storageBucket: 'spotifyproj0707.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcvyyhv3LBt30E62SBIfO0o0CPxA6KXR4',
    appId: '1:399269825726:web:dca585d3c767cfa34ea2ef',
    messagingSenderId: '399269825726',
    projectId: 'spotifyproj0707',
    authDomain: 'spotifyproj0707.firebaseapp.com',
    storageBucket: 'spotifyproj0707.appspot.com',
  );
}
