// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATKm7jG7pnZf0oZvXEB-VUNv0oOXMhK1w',
    appId: '1:420734507157:web:eb600fddc0b3256e74239c',
    messagingSenderId: '420734507157',
    projectId: 'projectspotify-1d7c3',
    authDomain: 'projectspotify-1d7c3.firebaseapp.com',
    storageBucket: 'projectspotify-1d7c3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8mr71Ke9i9IdLEUQUkf52EM9pcOY6ykg',
    appId: '1:420734507157:android:2887b57957bc97b074239c',
    messagingSenderId: '420734507157',
    projectId: 'projectspotify-1d7c3',
    storageBucket: 'projectspotify-1d7c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8w0GYKm7PkbSR0oZTFUI3wqh2V6oAO2Q',
    appId: '1:420734507157:ios:5da981af0b0f0a1474239c',
    messagingSenderId: '420734507157',
    projectId: 'projectspotify-1d7c3',
    storageBucket: 'projectspotify-1d7c3.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8w0GYKm7PkbSR0oZTFUI3wqh2V6oAO2Q',
    appId: '1:420734507157:ios:5da981af0b0f0a1474239c',
    messagingSenderId: '420734507157',
    projectId: 'projectspotify-1d7c3',
    storageBucket: 'projectspotify-1d7c3.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATKm7jG7pnZf0oZvXEB-VUNv0oOXMhK1w',
    appId: '1:420734507157:web:f5b2f145fdf095ca74239c',
    messagingSenderId: '420734507157',
    projectId: 'projectspotify-1d7c3',
    authDomain: 'projectspotify-1d7c3.firebaseapp.com',
    storageBucket: 'projectspotify-1d7c3.appspot.com',
  );
}
